// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SearchLog.proto

package org.fh.gae.log;

public final class SearchLog {
  private SearchLog() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SearchOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string sid = 1;
    boolean hasSid();
    String getSid();
    
    // required int64 timestamp = 2;
    boolean hasTimestamp();
    long getTimestamp();
    
    // required string tid = 3;
    boolean hasTid();
    String getTid();
    
    // required string requestId = 4;
    boolean hasRequestId();
    String getRequestId();
    
    // optional int32 resourceType = 5;
    boolean hasResourceType();
    int getResourceType();
    
    // optional string slotCode = 6;
    boolean hasSlotCode();
    String getSlotCode();
    
    // optional int32 slotType = 7;
    boolean hasSlotType();
    int getSlotType();
    
    // optional int32 width = 8;
    boolean hasWidth();
    int getWidth();
    
    // optional int32 height = 9;
    boolean hasHeight();
    int getHeight();
    
    // optional string materialType = 10;
    boolean hasMaterialType();
    String getMaterialType();
    
    // optional string mac = 11;
    boolean hasMac();
    String getMac();
    
    // optional string ip = 12;
    boolean hasIp();
    String getIp();
    
    // optional int32 planId = 13;
    boolean hasPlanId();
    int getPlanId();
    
    // optional int32 unitId = 14;
    boolean hasUnitId();
    int getUnitId();
    
    // optional string ideaId = 15;
    boolean hasIdeaId();
    String getIdeaId();
    
    // optional string adCode = 16;
    boolean hasAdCode();
    String getAdCode();
  }
  public static final class Search extends
      com.google.protobuf.GeneratedMessage
      implements SearchOrBuilder {
    // Use Search.newBuilder() to construct.
    private Search(Builder builder) {
      super(builder);
    }
    private Search(boolean noInit) {}
    
    private static final Search defaultInstance;
    public static Search getDefaultInstance() {
      return defaultInstance;
    }
    
    public Search getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.fh.gae.log.SearchLog.internal_static_org_fh_gae_log_Search_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.fh.gae.log.SearchLog.internal_static_org_fh_gae_log_Search_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string sid = 1;
    public static final int SID_FIELD_NUMBER = 1;
    private java.lang.Object sid_;
    public boolean hasSid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getSid() {
      java.lang.Object ref = sid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          sid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSidBytes() {
      java.lang.Object ref = sid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        sid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int64 timestamp = 2;
    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getTimestamp() {
      return timestamp_;
    }
    
    // required string tid = 3;
    public static final int TID_FIELD_NUMBER = 3;
    private java.lang.Object tid_;
    public boolean hasTid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getTid() {
      java.lang.Object ref = tid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          tid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTidBytes() {
      java.lang.Object ref = tid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        tid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string requestId = 4;
    public static final int REQUESTID_FIELD_NUMBER = 4;
    private java.lang.Object requestId_;
    public boolean hasRequestId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getRequestId() {
      java.lang.Object ref = requestId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          requestId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 resourceType = 5;
    public static final int RESOURCETYPE_FIELD_NUMBER = 5;
    private int resourceType_;
    public boolean hasResourceType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getResourceType() {
      return resourceType_;
    }
    
    // optional string slotCode = 6;
    public static final int SLOTCODE_FIELD_NUMBER = 6;
    private java.lang.Object slotCode_;
    public boolean hasSlotCode() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getSlotCode() {
      java.lang.Object ref = slotCode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          slotCode_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSlotCodeBytes() {
      java.lang.Object ref = slotCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        slotCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 slotType = 7;
    public static final int SLOTTYPE_FIELD_NUMBER = 7;
    private int slotType_;
    public boolean hasSlotType() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public int getSlotType() {
      return slotType_;
    }
    
    // optional int32 width = 8;
    public static final int WIDTH_FIELD_NUMBER = 8;
    private int width_;
    public boolean hasWidth() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public int getWidth() {
      return width_;
    }
    
    // optional int32 height = 9;
    public static final int HEIGHT_FIELD_NUMBER = 9;
    private int height_;
    public boolean hasHeight() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public int getHeight() {
      return height_;
    }
    
    // optional string materialType = 10;
    public static final int MATERIALTYPE_FIELD_NUMBER = 10;
    private java.lang.Object materialType_;
    public boolean hasMaterialType() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public String getMaterialType() {
      java.lang.Object ref = materialType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          materialType_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMaterialTypeBytes() {
      java.lang.Object ref = materialType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        materialType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string mac = 11;
    public static final int MAC_FIELD_NUMBER = 11;
    private java.lang.Object mac_;
    public boolean hasMac() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public String getMac() {
      java.lang.Object ref = mac_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          mac_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMacBytes() {
      java.lang.Object ref = mac_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        mac_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string ip = 12;
    public static final int IP_FIELD_NUMBER = 12;
    private java.lang.Object ip_;
    public boolean hasIp() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    public String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          ip_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 planId = 13;
    public static final int PLANID_FIELD_NUMBER = 13;
    private int planId_;
    public boolean hasPlanId() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    public int getPlanId() {
      return planId_;
    }
    
    // optional int32 unitId = 14;
    public static final int UNITID_FIELD_NUMBER = 14;
    private int unitId_;
    public boolean hasUnitId() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    public int getUnitId() {
      return unitId_;
    }
    
    // optional string ideaId = 15;
    public static final int IDEAID_FIELD_NUMBER = 15;
    private java.lang.Object ideaId_;
    public boolean hasIdeaId() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    public String getIdeaId() {
      java.lang.Object ref = ideaId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          ideaId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdeaIdBytes() {
      java.lang.Object ref = ideaId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        ideaId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string adCode = 16;
    public static final int ADCODE_FIELD_NUMBER = 16;
    private java.lang.Object adCode_;
    public boolean hasAdCode() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    public String getAdCode() {
      java.lang.Object ref = adCode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          adCode_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAdCodeBytes() {
      java.lang.Object ref = adCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        adCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      sid_ = "";
      timestamp_ = 0L;
      tid_ = "";
      requestId_ = "";
      resourceType_ = 0;
      slotCode_ = "";
      slotType_ = 0;
      width_ = 0;
      height_ = 0;
      materialType_ = "";
      mac_ = "";
      ip_ = "";
      planId_ = 0;
      unitId_ = 0;
      ideaId_ = "";
      adCode_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRequestId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTidBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getRequestIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, resourceType_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getSlotCodeBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, slotType_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, width_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, height_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getMaterialTypeBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, getMacBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(12, getIpBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeInt32(13, planId_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeInt32(14, unitId_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeBytes(15, getIdeaIdBytes());
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeBytes(16, getAdCodeBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTidBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getRequestIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, resourceType_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getSlotCodeBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, slotType_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, width_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, height_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getMaterialTypeBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getMacBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getIpBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, planId_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, unitId_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(15, getIdeaIdBytes());
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(16, getAdCodeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.fh.gae.log.SearchLog.Search parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.fh.gae.log.SearchLog.Search parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.fh.gae.log.SearchLog.Search parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.fh.gae.log.SearchLog.Search parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.fh.gae.log.SearchLog.Search parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.fh.gae.log.SearchLog.Search parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.fh.gae.log.SearchLog.Search parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.fh.gae.log.SearchLog.Search parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.fh.gae.log.SearchLog.Search parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.fh.gae.log.SearchLog.Search parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.fh.gae.log.SearchLog.Search prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.fh.gae.log.SearchLog.SearchOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.fh.gae.log.SearchLog.internal_static_org_fh_gae_log_Search_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.fh.gae.log.SearchLog.internal_static_org_fh_gae_log_Search_fieldAccessorTable;
      }
      
      // Construct using org.fh.gae.log.SearchLog.Search.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        sid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        tid_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        requestId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        resourceType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        slotCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        slotType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        width_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        height_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        materialType_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        mac_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        ip_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        planId_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        unitId_ = 0;
        bitField0_ = (bitField0_ & ~0x00002000);
        ideaId_ = "";
        bitField0_ = (bitField0_ & ~0x00004000);
        adCode_ = "";
        bitField0_ = (bitField0_ & ~0x00008000);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.fh.gae.log.SearchLog.Search.getDescriptor();
      }
      
      public org.fh.gae.log.SearchLog.Search getDefaultInstanceForType() {
        return org.fh.gae.log.SearchLog.Search.getDefaultInstance();
      }
      
      public org.fh.gae.log.SearchLog.Search build() {
        org.fh.gae.log.SearchLog.Search result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.fh.gae.log.SearchLog.Search buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.fh.gae.log.SearchLog.Search result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.fh.gae.log.SearchLog.Search buildPartial() {
        org.fh.gae.log.SearchLog.Search result = new org.fh.gae.log.SearchLog.Search(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sid_ = sid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.tid_ = tid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.requestId_ = requestId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.resourceType_ = resourceType_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.slotCode_ = slotCode_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.slotType_ = slotType_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.width_ = width_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.height_ = height_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.materialType_ = materialType_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.mac_ = mac_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.ip_ = ip_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.planId_ = planId_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.unitId_ = unitId_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.ideaId_ = ideaId_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.adCode_ = adCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.fh.gae.log.SearchLog.Search) {
          return mergeFrom((org.fh.gae.log.SearchLog.Search)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.fh.gae.log.SearchLog.Search other) {
        if (other == org.fh.gae.log.SearchLog.Search.getDefaultInstance()) return this;
        if (other.hasSid()) {
          setSid(other.getSid());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasTid()) {
          setTid(other.getTid());
        }
        if (other.hasRequestId()) {
          setRequestId(other.getRequestId());
        }
        if (other.hasResourceType()) {
          setResourceType(other.getResourceType());
        }
        if (other.hasSlotCode()) {
          setSlotCode(other.getSlotCode());
        }
        if (other.hasSlotType()) {
          setSlotType(other.getSlotType());
        }
        if (other.hasWidth()) {
          setWidth(other.getWidth());
        }
        if (other.hasHeight()) {
          setHeight(other.getHeight());
        }
        if (other.hasMaterialType()) {
          setMaterialType(other.getMaterialType());
        }
        if (other.hasMac()) {
          setMac(other.getMac());
        }
        if (other.hasIp()) {
          setIp(other.getIp());
        }
        if (other.hasPlanId()) {
          setPlanId(other.getPlanId());
        }
        if (other.hasUnitId()) {
          setUnitId(other.getUnitId());
        }
        if (other.hasIdeaId()) {
          setIdeaId(other.getIdeaId());
        }
        if (other.hasAdCode()) {
          setAdCode(other.getAdCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTimestamp()) {
          
          return false;
        }
        if (!hasTid()) {
          
          return false;
        }
        if (!hasRequestId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              sid_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              timestamp_ = input.readInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              tid_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              requestId_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              resourceType_ = input.readInt32();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              slotCode_ = input.readBytes();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              slotType_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              width_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              height_ = input.readInt32();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              materialType_ = input.readBytes();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000400;
              mac_ = input.readBytes();
              break;
            }
            case 98: {
              bitField0_ |= 0x00000800;
              ip_ = input.readBytes();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              planId_ = input.readInt32();
              break;
            }
            case 112: {
              bitField0_ |= 0x00002000;
              unitId_ = input.readInt32();
              break;
            }
            case 122: {
              bitField0_ |= 0x00004000;
              ideaId_ = input.readBytes();
              break;
            }
            case 130: {
              bitField0_ |= 0x00008000;
              adCode_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string sid = 1;
      private java.lang.Object sid_ = "";
      public boolean hasSid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getSid() {
        java.lang.Object ref = sid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          sid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sid_ = value;
        onChanged();
        return this;
      }
      public Builder clearSid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sid_ = getDefaultInstance().getSid();
        onChanged();
        return this;
      }
      void setSid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        sid_ = value;
        onChanged();
      }
      
      // required int64 timestamp = 2;
      private long timestamp_ ;
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getTimestamp() {
        return timestamp_;
      }
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000002;
        timestamp_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      
      // required string tid = 3;
      private java.lang.Object tid_ = "";
      public boolean hasTid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getTid() {
        java.lang.Object ref = tid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          tid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        tid_ = value;
        onChanged();
        return this;
      }
      public Builder clearTid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        tid_ = getDefaultInstance().getTid();
        onChanged();
        return this;
      }
      void setTid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        tid_ = value;
        onChanged();
      }
      
      // required string requestId = 4;
      private java.lang.Object requestId_ = "";
      public boolean hasRequestId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getRequestId() {
        java.lang.Object ref = requestId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          requestId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRequestId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        requestId_ = value;
        onChanged();
        return this;
      }
      public Builder clearRequestId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        requestId_ = getDefaultInstance().getRequestId();
        onChanged();
        return this;
      }
      void setRequestId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        requestId_ = value;
        onChanged();
      }
      
      // optional int32 resourceType = 5;
      private int resourceType_ ;
      public boolean hasResourceType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getResourceType() {
        return resourceType_;
      }
      public Builder setResourceType(int value) {
        bitField0_ |= 0x00000010;
        resourceType_ = value;
        onChanged();
        return this;
      }
      public Builder clearResourceType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        resourceType_ = 0;
        onChanged();
        return this;
      }
      
      // optional string slotCode = 6;
      private java.lang.Object slotCode_ = "";
      public boolean hasSlotCode() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getSlotCode() {
        java.lang.Object ref = slotCode_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          slotCode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSlotCode(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        slotCode_ = value;
        onChanged();
        return this;
      }
      public Builder clearSlotCode() {
        bitField0_ = (bitField0_ & ~0x00000020);
        slotCode_ = getDefaultInstance().getSlotCode();
        onChanged();
        return this;
      }
      void setSlotCode(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        slotCode_ = value;
        onChanged();
      }
      
      // optional int32 slotType = 7;
      private int slotType_ ;
      public boolean hasSlotType() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public int getSlotType() {
        return slotType_;
      }
      public Builder setSlotType(int value) {
        bitField0_ |= 0x00000040;
        slotType_ = value;
        onChanged();
        return this;
      }
      public Builder clearSlotType() {
        bitField0_ = (bitField0_ & ~0x00000040);
        slotType_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 width = 8;
      private int width_ ;
      public boolean hasWidth() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public int getWidth() {
        return width_;
      }
      public Builder setWidth(int value) {
        bitField0_ |= 0x00000080;
        width_ = value;
        onChanged();
        return this;
      }
      public Builder clearWidth() {
        bitField0_ = (bitField0_ & ~0x00000080);
        width_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 height = 9;
      private int height_ ;
      public boolean hasHeight() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public int getHeight() {
        return height_;
      }
      public Builder setHeight(int value) {
        bitField0_ |= 0x00000100;
        height_ = value;
        onChanged();
        return this;
      }
      public Builder clearHeight() {
        bitField0_ = (bitField0_ & ~0x00000100);
        height_ = 0;
        onChanged();
        return this;
      }
      
      // optional string materialType = 10;
      private java.lang.Object materialType_ = "";
      public boolean hasMaterialType() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public String getMaterialType() {
        java.lang.Object ref = materialType_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          materialType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMaterialType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        materialType_ = value;
        onChanged();
        return this;
      }
      public Builder clearMaterialType() {
        bitField0_ = (bitField0_ & ~0x00000200);
        materialType_ = getDefaultInstance().getMaterialType();
        onChanged();
        return this;
      }
      void setMaterialType(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000200;
        materialType_ = value;
        onChanged();
      }
      
      // optional string mac = 11;
      private java.lang.Object mac_ = "";
      public boolean hasMac() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public String getMac() {
        java.lang.Object ref = mac_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          mac_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMac(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        mac_ = value;
        onChanged();
        return this;
      }
      public Builder clearMac() {
        bitField0_ = (bitField0_ & ~0x00000400);
        mac_ = getDefaultInstance().getMac();
        onChanged();
        return this;
      }
      void setMac(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000400;
        mac_ = value;
        onChanged();
      }
      
      // optional string ip = 12;
      private java.lang.Object ip_ = "";
      public boolean hasIp() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      public String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setIp(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        ip_ = value;
        onChanged();
        return this;
      }
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000800);
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      void setIp(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000800;
        ip_ = value;
        onChanged();
      }
      
      // optional int32 planId = 13;
      private int planId_ ;
      public boolean hasPlanId() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      public int getPlanId() {
        return planId_;
      }
      public Builder setPlanId(int value) {
        bitField0_ |= 0x00001000;
        planId_ = value;
        onChanged();
        return this;
      }
      public Builder clearPlanId() {
        bitField0_ = (bitField0_ & ~0x00001000);
        planId_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 unitId = 14;
      private int unitId_ ;
      public boolean hasUnitId() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      public int getUnitId() {
        return unitId_;
      }
      public Builder setUnitId(int value) {
        bitField0_ |= 0x00002000;
        unitId_ = value;
        onChanged();
        return this;
      }
      public Builder clearUnitId() {
        bitField0_ = (bitField0_ & ~0x00002000);
        unitId_ = 0;
        onChanged();
        return this;
      }
      
      // optional string ideaId = 15;
      private java.lang.Object ideaId_ = "";
      public boolean hasIdeaId() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      public String getIdeaId() {
        java.lang.Object ref = ideaId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          ideaId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setIdeaId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
        ideaId_ = value;
        onChanged();
        return this;
      }
      public Builder clearIdeaId() {
        bitField0_ = (bitField0_ & ~0x00004000);
        ideaId_ = getDefaultInstance().getIdeaId();
        onChanged();
        return this;
      }
      void setIdeaId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00004000;
        ideaId_ = value;
        onChanged();
      }
      
      // optional string adCode = 16;
      private java.lang.Object adCode_ = "";
      public boolean hasAdCode() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      public String getAdCode() {
        java.lang.Object ref = adCode_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          adCode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAdCode(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00008000;
        adCode_ = value;
        onChanged();
        return this;
      }
      public Builder clearAdCode() {
        bitField0_ = (bitField0_ & ~0x00008000);
        adCode_ = getDefaultInstance().getAdCode();
        onChanged();
        return this;
      }
      void setAdCode(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00008000;
        adCode_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:org.fh.gae.log.Search)
    }
    
    static {
      defaultInstance = new Search(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.fh.gae.log.Search)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_fh_gae_log_Search_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_fh_gae_log_Search_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017SearchLog.proto\022\016org.fh.gae.log\"\220\002\n\006Se" +
      "arch\022\013\n\003sid\030\001 \001(\t\022\021\n\ttimestamp\030\002 \002(\003\022\013\n\003" +
      "tid\030\003 \002(\t\022\021\n\trequestId\030\004 \002(\t\022\024\n\014resource" +
      "Type\030\005 \001(\005\022\020\n\010slotCode\030\006 \001(\t\022\020\n\010slotType" +
      "\030\007 \001(\005\022\r\n\005width\030\010 \001(\005\022\016\n\006height\030\t \001(\005\022\024\n" +
      "\014materialType\030\n \001(\t\022\013\n\003mac\030\013 \001(\t\022\n\n\002ip\030\014" +
      " \001(\t\022\016\n\006planId\030\r \001(\005\022\016\n\006unitId\030\016 \001(\005\022\016\n\006" +
      "ideaId\030\017 \001(\t\022\016\n\006adCode\030\020 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_fh_gae_log_Search_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_fh_gae_log_Search_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_fh_gae_log_Search_descriptor,
              new java.lang.String[] { "Sid", "Timestamp", "Tid", "RequestId", "ResourceType", "SlotCode", "SlotType", "Width", "Height", "MaterialType", "Mac", "Ip", "PlanId", "UnitId", "IdeaId", "AdCode", },
              org.fh.gae.log.SearchLog.Search.class,
              org.fh.gae.log.SearchLog.Search.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
